global:
  image:
    registry: ghcr.io
    prefix: smartsolutionslab/baudoku
    tag: latest
    pullPolicy: IfNotPresent

services:
  projectsApi:
    name: projects-api
    replicaCount: 1
    image:
      name: projects-api
    port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    env: []

  documentationApi:
    name: documentation-api
    replicaCount: 1
    image:
      name: documentation-api
    port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    env: []

  syncApi:
    name: sync-api
    replicaCount: 1
    image:
      name: sync-api
    port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    env: []

  apiGateway:
    name: api-gateway
    replicaCount: 1
    image:
      name: api-gateway
    port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    env: []

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: baudoku.example.com
  tls: []
