{{- range $key, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  labels:
    app.kubernetes.io/name: {{ $svc.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ $svc.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ $svc.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
